# coding: utf-8

"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ICA_SDK
from ICA_SDK.models.read_sequencing_stats import ReadSequencingStats  # noqa: E501
from ICA_SDK.rest import ApiException

class TestReadSequencingStats(unittest.TestCase):
    """ReadSequencingStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReadSequencingStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ICA_SDK.models.read_sequencing_stats.ReadSequencingStats()  # noqa: E501
        if include_optional :
            return ReadSequencingStats(
                read_number = 56, 
                is_indexed = True, 
                total_cycles = 56, 
                yield_total = 1.337, 
                projected_total_yield = 1.337, 
                percent_aligned = 1.337, 
                error_rate = 1.337, 
                intensity_cycle1 = 1.337, 
                percent_gt_q30 = 1.337, 
                percent_gt_q30_last10_cycles = 1.337
            )
        else :
            return ReadSequencingStats(
                read_number = 56,
        )

    def testReadSequencingStats(self):
        """Test ReadSequencingStats"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
