# coding: utf-8

"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ICA_SDK
from ICA_SDK.api.analysis_version_definitions_api import AnalysisVersionDefinitionsApi  # noqa: E501
from ICA_SDK.rest import ApiException


class TestAnalysisVersionDefinitionsApi(unittest.TestCase):
    """AnalysisVersionDefinitionsApi unit test stubs"""

    def setUp(self):
        self.api = ICA_SDK.api.analysis_version_definitions_api.AnalysisVersionDefinitionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_analysis_version_definition(self):
        """Test case for archive_analysis_version_definition

        Archives the given Analysis Version Definition.  # noqa: E501
        """
        pass

    def test_create_analysis_version_definition(self):
        """Test case for create_analysis_version_definition

        Create an analysis version definition.  # noqa: E501
        """
        pass

    def test_get_analysis_version_definition(self):
        """Test case for get_analysis_version_definition

        Get a specific analysis definition version by version name.  # noqa: E501
        """
        pass

    def test_get_analysis_version_definition_by_id_or_urn(self):
        """Test case for get_analysis_version_definition_by_id_or_urn

        Get details of an analysis definition version by ID or URN.  # noqa: E501
        """
        pass

    def test_list_analysis_version_definitions(self):
        """Test case for list_analysis_version_definitions

        Get a list of analysis definition versions.  # noqa: E501
        """
        pass

    def test_merge_analysis_version_definition_acl(self):
        """Test case for merge_analysis_version_definition_acl

        Merge the access control list of an analysis version definition with the input access control list.  # noqa: E501
        """
        pass

    def test_remove_analysis_version_definition_acl(self):
        """Test case for remove_analysis_version_definition_acl

        Remove the access control list of an analysis version definition.  # noqa: E501
        """
        pass

    def test_render_analysis_version_definition_by_id_or_urn(self):
        """Test case for render_analysis_version_definition_by_id_or_urn

        Dynamically render an analysis definition version by ID or URN.  # noqa: E501
        """
        pass

    def test_replace_analysis_version_definition_acl(self):
        """Test case for replace_analysis_version_definition_acl

        Replace the access control list of an analysis version definition with the input access control list.  # noqa: E501
        """
        pass

    def test_unarchive_analysis_version_definition(self):
        """Test case for unarchive_analysis_version_definition

        Unarchive the given Analysis Version Definition.  # noqa: E501
        """
        pass

    def test_update_analysis_version_definition(self):
        """Test case for update_analysis_version_definition

        Update an analysis version definition.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
