# coding: utf-8

"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ICA_SDK
from ICA_SDK.api.sequencing_analysis_runs_api import SequencingAnalysisRunsApi  # noqa: E501
from ICA_SDK.rest import ApiException


class TestSequencingAnalysisRunsApi(unittest.TestCase):
    """SequencingAnalysisRunsApi unit test stubs"""

    def setUp(self):
        self.api = ICA_SDK.api.sequencing_analysis_runs_api.SequencingAnalysisRunsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sequencing_analysis_run(self):
        """Test case for get_sequencing_analysis_run

        Get SequencingAnalysisRun details.  # noqa: E501
        """
        pass

    def test_list_sequencing_analysis_runs(self):
        """Test case for list_sequencing_analysis_runs

        Get a list of analysis runs.  # noqa: E501
        """
        pass

    def test_sync_sequencing_analysis_run(self):
        """Test case for sync_sequencing_analysis_run

        Sync A SequencingAnalysisRun.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
