# coding: utf-8

"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ICA_SDK
from ICA_SDK.models.folder_writeable_response import FolderWriteableResponse  # noqa: E501
from ICA_SDK.rest import ApiException

class TestFolderWriteableResponse(unittest.TestCase):
    """FolderWriteableResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FolderWriteableResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ICA_SDK.models.folder_writeable_response.FolderWriteableResponse()  # noqa: E501
        if include_optional :
            return FolderWriteableResponse(
                id = '0', 
                name = '0', 
                volume_id = '0', 
                parent_folder_id = '0', 
                volume_name = '0', 
                tenant_id = '0', 
                sub_tenant_id = '0', 
                urn = '0', 
                path = '0', 
                acl = [
                    '0'
                    ], 
                inherited_acl = [
                    '0'
                    ], 
                time_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                created_by = '0', 
                time_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                modified_by = '0', 
                metadata = None, 
                volume_metadata = None, 
                job_status = 'None', 
                job_id = '0', 
                archive_job_storage_tier = 'None', 
                object_store_access = ICA_SDK.models.object_store_access.ObjectStoreAccess(
                    aws_s3_temporary_upload_credentials = ICA_SDK.models.aws_s3_temporary_upload_credentials.AwsS3TemporaryUploadCredentials(
                        access_key_id = '0', 
                        secret_access_key = '0', 
                        session_token = '0', 
                        region = '0', 
                        bucket_name = '0', 
                        key_prefix = '0', 
                        expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    direct_upload_credentials = ICA_SDK.models.direct_upload_credentials.DirectUploadCredentials(
                        prefix = '0', 
                        volume_name = '0', 
                        expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        file_creation_api_path = '0', 
                        file_upload_api_path = '0', 
                        upload_id = '0', ), 
                    session_id = '0', )
            )
        else :
            return FolderWriteableResponse(
        )

    def testFolderWriteableResponse(self):
        """Test FolderWriteableResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
