# coding: utf-8

"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ICA_SDK
from ICA_SDK.api.index_adapter_kits_api import IndexAdapterKitsApi  # noqa: E501
from ICA_SDK.rest import ApiException


class TestIndexAdapterKitsApi(unittest.TestCase):
    """IndexAdapterKitsApi unit test stubs"""

    def setUp(self):
        self.api = ICA_SDK.api.index_adapter_kits_api.IndexAdapterKitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_index_adapter_kit(self):
        """Test case for create_index_adapter_kit

        Create an index adapter kit.  # noqa: E501
        """
        pass

    def test_create_index_adapter_kit_by_definition(self):
        """Test case for create_index_adapter_kit_by_definition

        Create an index adapter kit using a definition string.  # noqa: E501
        """
        pass

    def test_delete_index_adapter_kit(self):
        """Test case for delete_index_adapter_kit

        Delete index adapter kit.  # noqa: E501
        """
        pass

    def test_get_index_adapter_kit(self):
        """Test case for get_index_adapter_kit

        Get index adapter kit details.  # noqa: E501
        """
        pass

    def test_list_index_adapter_kits(self):
        """Test case for list_index_adapter_kits

        Get a list of index adapter kits.  # noqa: E501
        """
        pass

    def test_merge_index_adapter_kit_acl(self):
        """Test case for merge_index_adapter_kit_acl

        Merge the access control list of an index adapter kit with the input access control list.  # noqa: E501
        """
        pass

    def test_remove_index_adapter_kit_acl(self):
        """Test case for remove_index_adapter_kit_acl

        Remove the access control list of an index adapter kit.  # noqa: E501
        """
        pass

    def test_replace_index_adapter_kit_acl(self):
        """Test case for replace_index_adapter_kit_acl

        Replace the access control list of an index adapter kit with the input access control list.  # noqa: E501
        """
        pass

    def test_update_index_adapter_kit(self):
        """Test case for update_index_adapter_kit

        Update an index adapter kit.  # noqa: E501
        """
        pass

    def test_update_index_adapter_kit_by_definition(self):
        """Test case for update_index_adapter_kit_by_definition

        Update an index adapter kit using a definition string.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
