# coding: utf-8

"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ICA_SDK.configuration import Configuration


class SupportedInstrumentPlatformAndTypes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'instrument_platform': 'str',
        'instrument_types': 'list[str]'
    }

    attribute_map = {
        'instrument_platform': 'instrumentPlatform',
        'instrument_types': 'instrumentTypes'
    }

    def __init__(self, instrument_platform=None, instrument_types=None, local_vars_configuration=None):  # noqa: E501
        """SupportedInstrumentPlatformAndTypes - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._instrument_platform = None
        self._instrument_types = None
        self.discriminator = None

        self.instrument_platform = instrument_platform
        if instrument_types is not None:
            self.instrument_types = instrument_types

    @property
    def instrument_platform(self):
        """Gets the instrument_platform of this SupportedInstrumentPlatformAndTypes.  # noqa: E501

        Instrument platform  # noqa: E501

        :return: The instrument_platform of this SupportedInstrumentPlatformAndTypes.  # noqa: E501
        :rtype: str
        """
        return self._instrument_platform

    @instrument_platform.setter
    def instrument_platform(self, instrument_platform):
        """Sets the instrument_platform of this SupportedInstrumentPlatformAndTypes.

        Instrument platform  # noqa: E501

        :param instrument_platform: The instrument_platform of this SupportedInstrumentPlatformAndTypes.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and instrument_platform is None:  # noqa: E501
            raise ValueError("Invalid value for `instrument_platform`, must not be `None`")  # noqa: E501

        self._instrument_platform = instrument_platform

    @property
    def instrument_types(self):
        """Gets the instrument_types of this SupportedInstrumentPlatformAndTypes.  # noqa: E501

        Instrument types  # noqa: E501

        :return: The instrument_types of this SupportedInstrumentPlatformAndTypes.  # noqa: E501
        :rtype: list[str]
        """
        return self._instrument_types

    @instrument_types.setter
    def instrument_types(self, instrument_types):
        """Sets the instrument_types of this SupportedInstrumentPlatformAndTypes.

        Instrument types  # noqa: E501

        :param instrument_types: The instrument_types of this SupportedInstrumentPlatformAndTypes.  # noqa: E501
        :type: list[str]
        """

        self._instrument_types = instrument_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupportedInstrumentPlatformAndTypes):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SupportedInstrumentPlatformAndTypes):
            return True

        return self.to_dict() != other.to_dict()
