# coding: utf-8

"""
    IAP Services

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ICA_SDK.configuration import Configuration


class UpdateLibraryRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'description': 'str',
        'status': 'str',
        'library_prep_kit_id': 'str',
        'index_adapter_kit_id': 'str',
        'index_container_position': 'str',
        'index1_name': 'str',
        'index2_name': 'str',
        'index1_sequence': 'str',
        'index2_sequence': 'str',
        'adapter_sequence_read1': 'str',
        'adapter_sequence_read2': 'str',
        'acl': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'status': 'status',
        'library_prep_kit_id': 'libraryPrepKitId',
        'index_adapter_kit_id': 'indexAdapterKitId',
        'index_container_position': 'indexContainerPosition',
        'index1_name': 'index1Name',
        'index2_name': 'index2Name',
        'index1_sequence': 'index1Sequence',
        'index2_sequence': 'index2Sequence',
        'adapter_sequence_read1': 'adapterSequenceRead1',
        'adapter_sequence_read2': 'adapterSequenceRead2',
        'acl': 'acl'
    }

    def __init__(self, name=None, description=None, status=None, library_prep_kit_id=None, index_adapter_kit_id=None, index_container_position=None, index1_name=None, index2_name=None, index1_sequence=None, index2_sequence=None, adapter_sequence_read1=None, adapter_sequence_read2=None, acl=None, local_vars_configuration=None):  # noqa: E501
        """UpdateLibraryRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._description = None
        self._status = None
        self._library_prep_kit_id = None
        self._index_adapter_kit_id = None
        self._index_container_position = None
        self._index1_name = None
        self._index2_name = None
        self._index1_sequence = None
        self._index2_sequence = None
        self._adapter_sequence_read1 = None
        self._adapter_sequence_read2 = None
        self._acl = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if status is not None:
            self.status = status
        if library_prep_kit_id is not None:
            self.library_prep_kit_id = library_prep_kit_id
        if index_adapter_kit_id is not None:
            self.index_adapter_kit_id = index_adapter_kit_id
        if index_container_position is not None:
            self.index_container_position = index_container_position
        if index1_name is not None:
            self.index1_name = index1_name
        if index2_name is not None:
            self.index2_name = index2_name
        if index1_sequence is not None:
            self.index1_sequence = index1_sequence
        if index2_sequence is not None:
            self.index2_sequence = index2_sequence
        if adapter_sequence_read1 is not None:
            self.adapter_sequence_read1 = adapter_sequence_read1
        if adapter_sequence_read2 is not None:
            self.adapter_sequence_read2 = adapter_sequence_read2
        if acl is not None:
            self.acl = acl

    @property
    def name(self):
        """Gets the name of this UpdateLibraryRequest.  # noqa: E501

        Name of the library. This field is case-insensitive.  # noqa: E501

        :return: The name of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdateLibraryRequest.

        Name of the library. This field is case-insensitive.  # noqa: E501

        :param name: The name of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 140):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `140`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 0):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this UpdateLibraryRequest.  # noqa: E501

        Description of the library  # noqa: E501

        :return: The description of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateLibraryRequest.

        Description of the library  # noqa: E501

        :param description: The description of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) > 8192):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `8192`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) < 0):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `0`")  # noqa: E501

        self._description = description

    @property
    def status(self):
        """Gets the status of this UpdateLibraryRequest.  # noqa: E501

        Status of the library  # noqa: E501

        :return: The status of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this UpdateLibraryRequest.

        Status of the library  # noqa: E501

        :param status: The status of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["Active", "Failed", "Canceled", "Consumed"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def library_prep_kit_id(self):
        """Gets the library_prep_kit_id of this UpdateLibraryRequest.  # noqa: E501

        ID of the library prep kit used to prepare the library  # noqa: E501

        :return: The library_prep_kit_id of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._library_prep_kit_id

    @library_prep_kit_id.setter
    def library_prep_kit_id(self, library_prep_kit_id):
        """Sets the library_prep_kit_id of this UpdateLibraryRequest.

        ID of the library prep kit used to prepare the library  # noqa: E501

        :param library_prep_kit_id: The library_prep_kit_id of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                library_prep_kit_id is not None and len(library_prep_kit_id) > 50):
            raise ValueError("Invalid value for `library_prep_kit_id`, length must be less than or equal to `50`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                library_prep_kit_id is not None and len(library_prep_kit_id) < 0):
            raise ValueError("Invalid value for `library_prep_kit_id`, length must be greater than or equal to `0`")  # noqa: E501

        self._library_prep_kit_id = library_prep_kit_id

    @property
    def index_adapter_kit_id(self):
        """Gets the index_adapter_kit_id of this UpdateLibraryRequest.  # noqa: E501

        ID of the index kit used to prepare the library  # noqa: E501

        :return: The index_adapter_kit_id of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._index_adapter_kit_id

    @index_adapter_kit_id.setter
    def index_adapter_kit_id(self, index_adapter_kit_id):
        """Sets the index_adapter_kit_id of this UpdateLibraryRequest.

        ID of the index kit used to prepare the library  # noqa: E501

        :param index_adapter_kit_id: The index_adapter_kit_id of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                index_adapter_kit_id is not None and len(index_adapter_kit_id) > 50):
            raise ValueError("Invalid value for `index_adapter_kit_id`, length must be less than or equal to `50`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index_adapter_kit_id is not None and len(index_adapter_kit_id) < 0):
            raise ValueError("Invalid value for `index_adapter_kit_id`, length must be greater than or equal to `0`")  # noqa: E501

        self._index_adapter_kit_id = index_adapter_kit_id

    @property
    def index_container_position(self):
        """Gets the index_container_position of this UpdateLibraryRequest.  # noqa: E501

        The container position (well or plate+well position) for the library that is using an index adapter kit with fixed index position  # noqa: E501

        :return: The index_container_position of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._index_container_position

    @index_container_position.setter
    def index_container_position(self, index_container_position):
        """Sets the index_container_position of this UpdateLibraryRequest.

        The container position (well or plate+well position) for the library that is using an index adapter kit with fixed index position  # noqa: E501

        :param index_container_position: The index_container_position of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                index_container_position is not None and len(index_container_position) > 8):
            raise ValueError("Invalid value for `index_container_position`, length must be less than or equal to `8`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index_container_position is not None and len(index_container_position) < 0):
            raise ValueError("Invalid value for `index_container_position`, length must be greater than or equal to `0`")  # noqa: E501

        self._index_container_position = index_container_position

    @property
    def index1_name(self):
        """Gets the index1_name of this UpdateLibraryRequest.  # noqa: E501

        Index 1 name  # noqa: E501

        :return: The index1_name of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._index1_name

    @index1_name.setter
    def index1_name(self, index1_name):
        """Sets the index1_name of this UpdateLibraryRequest.

        Index 1 name  # noqa: E501

        :param index1_name: The index1_name of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                index1_name is not None and len(index1_name) > 255):
            raise ValueError("Invalid value for `index1_name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index1_name is not None and len(index1_name) < 0):
            raise ValueError("Invalid value for `index1_name`, length must be greater than or equal to `0`")  # noqa: E501

        self._index1_name = index1_name

    @property
    def index2_name(self):
        """Gets the index2_name of this UpdateLibraryRequest.  # noqa: E501

        Index 2 name  # noqa: E501

        :return: The index2_name of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._index2_name

    @index2_name.setter
    def index2_name(self, index2_name):
        """Sets the index2_name of this UpdateLibraryRequest.

        Index 2 name  # noqa: E501

        :param index2_name: The index2_name of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                index2_name is not None and len(index2_name) > 255):
            raise ValueError("Invalid value for `index2_name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index2_name is not None and len(index2_name) < 0):
            raise ValueError("Invalid value for `index2_name`, length must be greater than or equal to `0`")  # noqa: E501

        self._index2_name = index2_name

    @property
    def index1_sequence(self):
        """Gets the index1_sequence of this UpdateLibraryRequest.  # noqa: E501

        Index 1 sequence  # noqa: E501

        :return: The index1_sequence of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._index1_sequence

    @index1_sequence.setter
    def index1_sequence(self, index1_sequence):
        """Sets the index1_sequence of this UpdateLibraryRequest.

        Index 1 sequence  # noqa: E501

        :param index1_sequence: The index1_sequence of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                index1_sequence is not None and len(index1_sequence) > 10):
            raise ValueError("Invalid value for `index1_sequence`, length must be less than or equal to `10`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index1_sequence is not None and len(index1_sequence) < 0):
            raise ValueError("Invalid value for `index1_sequence`, length must be greater than or equal to `0`")  # noqa: E501

        self._index1_sequence = index1_sequence

    @property
    def index2_sequence(self):
        """Gets the index2_sequence of this UpdateLibraryRequest.  # noqa: E501

        Index 2 sequence  # noqa: E501

        :return: The index2_sequence of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._index2_sequence

    @index2_sequence.setter
    def index2_sequence(self, index2_sequence):
        """Sets the index2_sequence of this UpdateLibraryRequest.

        Index 2 sequence  # noqa: E501

        :param index2_sequence: The index2_sequence of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                index2_sequence is not None and len(index2_sequence) > 10):
            raise ValueError("Invalid value for `index2_sequence`, length must be less than or equal to `10`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                index2_sequence is not None and len(index2_sequence) < 0):
            raise ValueError("Invalid value for `index2_sequence`, length must be greater than or equal to `0`")  # noqa: E501

        self._index2_sequence = index2_sequence

    @property
    def adapter_sequence_read1(self):
        """Gets the adapter_sequence_read1 of this UpdateLibraryRequest.  # noqa: E501

        Adapter sequence read 1  # noqa: E501

        :return: The adapter_sequence_read1 of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._adapter_sequence_read1

    @adapter_sequence_read1.setter
    def adapter_sequence_read1(self, adapter_sequence_read1):
        """Sets the adapter_sequence_read1 of this UpdateLibraryRequest.

        Adapter sequence read 1  # noqa: E501

        :param adapter_sequence_read1: The adapter_sequence_read1 of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                adapter_sequence_read1 is not None and len(adapter_sequence_read1) > 128):
            raise ValueError("Invalid value for `adapter_sequence_read1`, length must be less than or equal to `128`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                adapter_sequence_read1 is not None and len(adapter_sequence_read1) < 0):
            raise ValueError("Invalid value for `adapter_sequence_read1`, length must be greater than or equal to `0`")  # noqa: E501

        self._adapter_sequence_read1 = adapter_sequence_read1

    @property
    def adapter_sequence_read2(self):
        """Gets the adapter_sequence_read2 of this UpdateLibraryRequest.  # noqa: E501

        Adapter sequence read 2  # noqa: E501

        :return: The adapter_sequence_read2 of this UpdateLibraryRequest.  # noqa: E501
        :rtype: str
        """
        return self._adapter_sequence_read2

    @adapter_sequence_read2.setter
    def adapter_sequence_read2(self, adapter_sequence_read2):
        """Sets the adapter_sequence_read2 of this UpdateLibraryRequest.

        Adapter sequence read 2  # noqa: E501

        :param adapter_sequence_read2: The adapter_sequence_read2 of this UpdateLibraryRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                adapter_sequence_read2 is not None and len(adapter_sequence_read2) > 128):
            raise ValueError("Invalid value for `adapter_sequence_read2`, length must be less than or equal to `128`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                adapter_sequence_read2 is not None and len(adapter_sequence_read2) < 0):
            raise ValueError("Invalid value for `adapter_sequence_read2`, length must be greater than or equal to `0`")  # noqa: E501

        self._adapter_sequence_read2 = adapter_sequence_read2

    @property
    def acl(self):
        """Gets the acl of this UpdateLibraryRequest.  # noqa: E501


        :return: The acl of this UpdateLibraryRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._acl

    @acl.setter
    def acl(self, acl):
        """Sets the acl of this UpdateLibraryRequest.


        :param acl: The acl of this UpdateLibraryRequest.  # noqa: E501
        :type: list[str]
        """

        self._acl = acl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateLibraryRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateLibraryRequest):
            return True

        return self.to_dict() != other.to_dict()
